language: java
jdk: openjdk8

before_install:
  - chmod +x ./gradlew
  - ./gradlew --no-daemon startDb createDb

install:
  - ./gradlew --no-daemon assemble

script:
  - ./gradlew --no-daemon test

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  apt:
    packages:
      - openjdk-8-jdk